export const STATE_SCHEMA_ENUM_LOCK = {
  snapshot: {
    schemaVersion: "8",
    Status: [
      "waiting_for_assessment",
      "waiting_for_owner",
      "waiting_for_decision",
      "waiting_for_review",
      "waiting_for_revision",
      "waiting_for_reply",
      "waiting_for_work",
      "waiting_for_unblock",
      "waiting_for_automation",
      "waiting_for_merge",
      "in_progress",
      "unknown",
      "terminal_merged",
      "terminal_completed",
      "terminal_not_planned",
    ],
    WaitClass: [
      "assessment",
      "owner",
      "decision",
      "review",
      "revision",
      "reply",
      "work",
      "merge",
      "automation",
      "blockedParent",
      "notApplicable",
    ],
  },
  history: {
    schemaVersion: "2",
    Status: [
      "waiting_for_assessment",
      "waiting_for_owner",
      "waiting_for_decision",
      "waiting_for_review",
      "waiting_for_revision",
      "waiting_for_reply",
      "waiting_for_work",
      "waiting_for_unblock",
      "waiting_for_automation",
      "waiting_for_merge",
      "in_progress",
      "unknown",
      "terminal_merged",
      "terminal_completed",
      "terminal_not_planned",
    ],
  },
  notificationLedger: {
    schemaVersion: "2",
    reasonCode: [
      "none",
      "assessment_overdue",
      "owner_overdue",
      "decision_overdue",
      "review_overdue",
      "revision_overdue",
      "reply_overdue",
      "owner_unknown",
      "blocker_overdue",
      "newly_unblocked",
      "dependency_cycle",
      "responsibility_changed",
      "merge_overdue",
      "automation_stuck",
    ],
  },
} as const;
