import { z } from "zod";

export const performanceDetailEventSchema = z.strictObject({
  step: z.enum([
    "checkpoint_payload_created",
    "checkpoint_encoded",
    "checkpoint_artifact_encoded",
    "checkpoint_sidecar_encoded",
    "checkpoint_frames_encoded",
    "checkpoint_decoded",
    "checkpoint_base_snapshot_read",
    "checkpoint_base_ledger_read",
    "checkpoint_bound",
    "closure_current_complete",
    "closure_prior_records_complete",
    "cas_previous_transaction_verified",
    "cas_adapter_commit_completed",
    "cas_candidate_tree_read",
    "cas_current_transaction_verified",
    "cas_commit_chain_verified",
    "cas_published",
    "receipt_tree_read",
    "receipt_commit_chain_verified",
    "receipt_created",
    "committed_tree_read",
    "committed_receipt_reobserved",
    "committed_public_safety_checked",
    "notification_initial_tree_read",
    "notification_initial_receipt_reobserved",
    "notification_current_tree_verified",
    "notification_history_restored",
    "notification_settlement_cas_started",
    "notification_settlement_cas_completed",
    "notification_settlement_receipt_reobserved",
    "notification_finalization_ready",
    "notification_settlement_failure_classification_started",
    "notification_failure_boundary_started",
    "run_finalization_started",
    "run_finalization_settlement_verified",
    "run_finalization_current_tree_verified",
    "run_finalization_cas_started",
    "run_finalization_cas_completed",
    "run_finalization_receipt_started",
    "run_finalization_receipt_completed",
    "run_finalization_completed",
    "state_snapshot_full_validation",
    "state_snapshot_proof_reused",
    "state_record_full_validation",
    "state_record_proof_reused",
    "state_history_full_validation",
    "state_history_proof_reused",
  ]),
  count: z.number().int().nonnegative().optional(),
  bytes: z.number().int().nonnegative().optional(),
});

export type PerformanceDetailEvent = z.output<typeof performanceDetailEventSchema>;

export type PerformanceDetailObserver = (event: PerformanceDetailEvent) => void;
